### ISSUE TITLE
试试github codespace吧

### ISSUE THREAD

**Issue by surfissh** [54145a/daoscus#1]
每次修改都要commit一次才能看到结果也挺累的（）

**Comment by 54145a** [comment]
codespaces进入时会跳转到github.com/codespace/xxx，有的时候会被阻断 :(，学习机无法安装用于解决这种阻断的软件，所以只能用网页版vscode改代码用pages看结果…… ~~而且还能刷贡献~~

**Comment by surfissh** [comment]
az
